### ISSUE TITLE
Queries

### ISSUE THREAD

**Issue by WinstonHartnett** [WinstonHartnett/recs#6]
## TODO

- [ ] Finish query combinators
- [ ] Test performance
- [ ] Query access inheritance
- [ ] Extra system properties (threadlocal, uncached, etc.)
